version: '3'
services:
  terraform:
    container_name: terraform
    build:
      context: .docker
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/terraform
    working_dir: /terraform/src/prod
    entrypoint: ash
    tty: true
